[package]
name = "tty_8080"
version = "0.1.1"
edition = "2024"

[dependencies]
serde_json = {workspace = true}
lib8080_msg = {workspace = true}
tokio = {workspace = true}
cursive = { version = "0.21.1", features = ["crossterm-backend"] }
clap = { version = "4.6.1", features = ["derive"] }
color-print = "0.3.7"
